# This file generates the GitHub Actions matrix.
# Shield variants:
#   k3yb_it          - no display
#   k3yb_it_oled32   - SSD1306 128x32 OLED
#   k3yb_it_oled128  - SSD1327 128x128 OLED
---
include:
  - board: nice_nano_v2
    shield: k3yb_it
  - board: nice_nano_v2
    shield: k3yb_it_oled32
    artifact-name: k3yb_it_SSD1306_128x32
  - board: nice_nano_v2
    shield: k3yb_it_oled128
    artifact-name: k3yb_it_SSD1327_128x128
  - board: nice_nano_v2
    shield: k3yb_it_oled32
    snippet: zmk-usb-logging
    artifact-name: k3yb_it_SSD1306_128x32_debug
  - board: nice_nano_v2
    shield: k3yb_it_oled128
    snippet: zmk-usb-logging
    artifact-name: k3yb_it_SSD1327_128x128_debug
  - board: nice_nano_v2
    shield: k3yb_it_oled128
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_DISPLAY=n -DCONFIG_DISPLAY=y -DCONFIG_K3YB_SSD1327_TEST_PATTERN=y
    artifact-name: k3yb_it_SSD1327_128x128_testpattern
  # bisect variants (temporary)
  - board: nice_nano_v2
    shield: k3yb_it_oled32
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_K3YB_STATUS_MINIMAL=y
    artifact-name: bisect_32_debug_minimal_ui
  - board: nice_nano_v2
    shield: k3yb_it_oled32
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_DISPLAY=n
    artifact-name: bisect_32_debug_nodisplay
  - board: nice_nano_v2
    shield: k3yb_it_oled32
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=n -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
    artifact-name: bisect_32_debug_builtinscreen
